package RaihanJmartFH;

public enum ProductCategory{
    BOOK, KITCHEN, ELECTRONIC, FASHION, GAMING, GADGET, MOTHERCARE, 
    COSMETICS, HEALTHCARE, FURNITURE, JEWELRY, TOYS, FNB, SPORTS, AUTOMOVIE, 
    PETCARE, ART_CRAFT, CARPENTRY, MISCELLANEOUS, PROPERTY, TRAVEL, WEDDING
}



