package BrianCJmartFH;

enum ProductCategory {
    BOOK, KITCHEN, ELECTRONIC, FASHION, GAMING, GADGET, MOTHERCARE, COSMETICS, HEALTHCARE, FURNITURE,
    JEWELRY, TOYS, FNB, STATIONERY, SPORTS, AUTOMOTIVE, PETCARE, ART_CRAFT, CARPENTRY, MISCELLANIOUS,
    PROPERTY, TRAVEL, WEDDING
}