package qalbuJmartFH;

enum ProductCategory{
    BOOK, KITCHEN, ELECTRONIC, FASHION, GAMING, GADGET, MOTHERCARE, COSMETICS,
    HEALTHCARE, FURNITURE, JEWERLY, TOYS, FNB, STATIONERY, SPORTS, AUTOMOTIVE,
    PETCARE, ART_CRAFT, CARPENTRY, MISCELLANEOUS, PROPERTY, TRAVEL, WEDDING;
}

